# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
gems:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"

# Site settings
title: Stay hungry, stay foolish.
# subtitle: "하고싶은 일을 하자 :)"
email: kitchu@naver.com
name: Kitchu
description: >
  Omniveloper`s dev-log :)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kitchu0401.github.io" # the base hostname & protocol for your site
cover: "/assets/header_image.jpg"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Disqus comments
disqus_shortname: omniveloper

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: review
    desc: "세미나 및 스터디 후기를 정리합니다."

  - cat: hobby
    desc: "취향의 기록."
    
# Include in the "Share" section of posts
social:

  - name: GitHub
    icon: github
    username: kitchu0401
    url: https://github.com/kitchu0401
    desc: Fork me on GitHub
    share: false

  # - name: LinkedIn
  #   icon: linkedin
  #   username: Ben Centra
  #   url: https://www.linkedin.com/pub/ben-centra/47/769/60a
  #   desc: Connect with me on LinkedIn
  #   share: true

  - name: Instagram
    icon: instagram
    username:
    url:
    desc: Follow me on Instagram
    share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

    os_repo: "https://github.com/bencentra/centrarium.com"
    os_rcs_type: "git"
    os_src: "git@github.com:bencentra/centrarium.com.git"
